title: Scratch Exemplar
hero_image: images/banner.png
description: An example Scratch project
version: 4
listed: false
copyedit: false
last_tested: 2019-03-21
steps:
  - title: Introduction
  - title: Starting the project
  - title: Using blocks
  - title: Highlighting text in block colours
  - title: Hints
  - title: "Challenge: its a challenge"
  challenge: true
  - title: 'What next?'
