title: scratch-exemplar
hero_image: images/banner.png
description: scratch-exemplar description
version: 4
listed: false
copyedit: false
last_tested: "2019-03-21"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
